# Metadata and Label Preparation

This notebook prepares the metadata used to train the model.  
The pathology field is converted into binary labels so the images can be used for classification.

In [1]:
import os
import pandas as pd
import numpy as np

print("Libraries imported")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Libraries imported
Pandas version: 2.2.2
NumPy version: 2.0.2

## Inspect metadata
Set project paths for metadata files and images.

In [4]:
# Define project paths
PROJECT_ROOT = "/content/drive/MyDrive/breast_cancer_detection"
RAW_DATA_PATH = os.path.join(PROJECT_ROOT, "raw_data")
CSV_PATH = os.path.join(RAW_DATA_PATH, "csv")
JPEG_PATH = os.path.join(RAW_DATA_PATH, "jpeg")


print("PROJECT PATHS")

print(f"Project Root:  {PROJECT_ROOT}")
print(f"Raw Data:      {RAW_DATA_PATH}")
print(f"CSV Metadata:  {CSV_PATH}")
print(f"JPEG Images:   {JPEG_PATH}")

PROJECT PATHS
Project Root:  /content/drive/MyDrive/breast_cancer_detection
Raw Data:      /content/drive/MyDrive/breast_cancer_detection/raw_data
CSV Metadata:  /content/drive/MyDrive/breast_cancer_detection/raw_data/csv
JPEG Images:   /content/drive/MyDrive/breast_cancer_detection/raw_data/jpeg

## Inspect metadata
Check required folders and metadata CSV files.

In [ ]:
print("CHECKING FOLDERS AND FILES")

# Check folders
folders_to_check = [
    ("Raw Data", RAW_DATA_PATH),
    ("CSV Metadata", CSV_PATH),
    ("JPEG Images", JPEG_PATH)
]

print("\nFolders:")
all_folders_exist = True
for name, path in folders_to_check:
    exists = os.path.exists(path)
    status = "OK" if exists else "MISSING"
    print(f"  {status} {name}: {path}")
    if not exists:
        all_folders_exist = False

# Check CSV files
csv_files = [
    "mass_case_description_train_set.csv",
    "mass_case_description_test_set.csv",
    "calc_case_description_train_set.csv",
    "calc_case_description_test_set.csv"
]

print("\nCSV files:")
all_files_exist = True
for csv_file in csv_files:
    file_path = os.path.join(CSV_PATH, csv_file)
    exists = os.path.exists(file_path)
    status = "OK" if exists else "MISSING"
    print(f"  {status} {csv_file}")
    if not exists:
        all_files_exist = False


if all_folders_exist and all_files_exist:
    print("All required folders and files found")
else:
    print("Some folders or files are missing")
    print("Check dataset extraction")

CHECKING FOLDERS AND FILES

Folders:
  OK Raw Data: /content/drive/MyDrive/breast_cancer_detection/raw_data
  OK CSV Metadata: /content/drive/MyDrive/breast_cancer_detection/raw_data/csv
  OK JPEG Images: /content/drive/MyDrive/breast_cancer_detection/raw_data/jpeg

CSV files:
  OK mass_case_description_train_set.csv
  OK mass_case_description_test_set.csv
  OK calc_case_description_train_set.csv
  OK calc_case_description_test_set.csv
All required folders and files found

## Load metadata
Load metadata CSV files into dataframes.

In [6]:
print("LOADING CSV FILES")

# Load each CSV file
mass_train = pd.read_csv(os.path.join(CSV_PATH, "mass_case_description_train_set.csv"))
print("Loaded: mass_case_description_train_set.csv")

mass_test = pd.read_csv(os.path.join(CSV_PATH, "mass_case_description_test_set.csv"))
print("Loaded: mass_case_description_test_set.csv")

calc_train = pd.read_csv(os.path.join(CSV_PATH, "calc_case_description_train_set.csv"))
print("Loaded: calc_case_description_train_set.csv")

calc_test = pd.read_csv(os.path.join(CSV_PATH, "calc_case_description_test_set.csv"))
print("Loaded: calc_case_description_test_set.csv")

print("\nAll CSV files loaded")

LOADING CSV FILES
Loaded: mass_case_description_train_set.csv
Loaded: mass_case_description_test_set.csv
Loaded: calc_case_description_train_set.csv
Loaded: calc_case_description_test_set.csv

All CSV files loaded

## Inspect metadata
Review dataframe shape, columns, and sample rows.

In [7]:
print("MASS TRAINING SET")

print(f"\nShape: {mass_train.shape[0]} rows × {mass_train.shape[1]} columns")
print(f"\nColumns ({len(mass_train.columns)}):")
for i, col in enumerate(mass_train.columns, 1):
    print(f"  {i}. {col}")
print("\nFirst 5 rows:")

mass_train.head()

MASS TRAINING SET

Shape: 1318 rows × 14 columns

Columns (14):
  1. patient_id
  2. breast_density
  3. left or right breast
  4. image view
  5. abnormality id
  6. abnormality type
  7. mass shape
  8. mass margins
  9. assessment
  10. pathology
  11. subtlety
  12. image file path
  13. cropped image file path
  14. ROI mask file path

First 5 rows:

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00001,3,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...
1,P_00001,3,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...
2,P_00004,3,LEFT,CC,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...
3,P_00004,3,LEFT,MLO,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...
4,P_00004,3,RIGHT,MLO,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....

In [8]:
print("MASS TEST SET")

print(f"\nShape: {mass_test.shape[0]} rows × {mass_test.shape[1]} columns")
print(f"\nColumns ({len(mass_test.columns)}):")
for i, col in enumerate(mass_test.columns, 1):
    print(f"  {i}. {col}")
print("\nFirst 5 rows:")

mass_test.head()

MASS TEST SET

Shape: 378 rows × 14 columns

Columns (14):
  1. patient_id
  2. breast_density
  3. left or right breast
  4. image view
  5. abnormality id
  6. abnormality type
  7. mass shape
  8. mass margins
  9. assessment
  10. pathology
  11. subtlety
  12. image file path
  13. cropped image file path
  14. ROI mask file path

First 5 rows:

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00016,4,LEFT,CC,1,mass,IRREGULAR,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00016_LEFT_CC/1.3.6.1.4.1.9590.100...,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.1...,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.1...
1,P_00016,4,LEFT,MLO,1,mass,IRREGULAR,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00016_LEFT_MLO/1.3.6.1.4.1.9590.10...,Mass-Test_P_00016_LEFT_MLO_1/1.3.6.1.4.1.9590....,Mass-Test_P_00016_LEFT_MLO_1/1.3.6.1.4.1.9590....
2,P_00017,2,LEFT,CC,1,mass,ROUND,CIRCUMSCRIBED,4,MALIGNANT,4,Mass-Test_P_00017_LEFT_CC/1.3.6.1.4.1.9590.100...,Mass-Test_P_00017_LEFT_CC_1/1.3.6.1.4.1.9590.1...,Mass-Test_P_00017_LEFT_CC_1/1.3.6.1.4.1.9590.1...
3,P_00017,2,LEFT,MLO,1,mass,ROUND,ILL_DEFINED,4,MALIGNANT,4,Mass-Test_P_00017_LEFT_MLO/1.3.6.1.4.1.9590.10...,Mass-Test_P_00017_LEFT_MLO_1/1.3.6.1.4.1.9590....,Mass-Test_P_00017_LEFT_MLO_1/1.3.6.1.4.1.9590....
4,P_00032,3,RIGHT,CC,1,mass,ROUND,OBSCURED,0,BENIGN,2,Mass-Test_P_00032_RIGHT_CC/1.3.6.1.4.1.9590.10...,Mass-Test_P_00032_RIGHT_CC_1/1.3.6.1.4.1.9590....,Mass-Test_P_00032_RIGHT_CC_1/1.3.6.1.4.1.9590....

In [9]:
print("CALCIFICATION TRAINING SET")

print(f"\nShape: {calc_train.shape[0]} rows × {calc_train.shape[1]} columns")
print(f"\nColumns ({len(calc_train.columns)}):")
for i, col in enumerate(calc_train.columns, 1):
    print(f"  {i}. {col}")
print("\nFirst 5 rows:")

calc_train.head()

CALCIFICATION TRAINING SET

Shape: 1546 rows × 14 columns

Columns (14):
  1. patient_id
  2. breast density
  3. left or right breast
  4. image view
  5. abnormality id
  6. abnormality type
  7. calc type
  8. calc distribution
  9. assessment
  10. pathology
  11. subtlety
  12. image file path
  13. cropped image file path
  14. ROI mask file path

First 5 rows:

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00005,3,RIGHT,CC,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.959...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...
1,P_00005,3,RIGHT,MLO,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.95...,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....
2,P_00007,4,LEFT,CC,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...
3,P_00007,4,LEFT,MLO,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.959...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...
4,P_00008,1,LEFT,CC,1,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...

In [10]:
print("CALCIFICATION TEST SET")

print(f"\nShape: {calc_test.shape[0]} rows × {calc_test.shape[1]} columns")
print(f"\nColumns ({len(calc_test.columns)}):")
for i, col in enumerate(calc_test.columns, 1):
    print(f"  {i}. {col}")
print("\nFirst 5 rows:")

calc_test.head()

CALCIFICATION TEST SET

Shape: 326 rows × 14 columns

Columns (14):
  1. patient_id
  2. breast density
  3. left or right breast
  4. image view
  5. abnormality id
  6. abnormality type
  7. calc type
  8. calc distribution
  9. assessment
  10. pathology
  11. subtlety
  12. image file path
  13. cropped image file path
  14. ROI mask file path

First 5 rows:

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00038,2,LEFT,CC,1,calcification,PUNCTATE-PLEOMORPHIC,CLUSTERED,4,BENIGN,2,Calc-Test_P_00038_LEFT_CC/1.3.6.1.4.1.9590.100...,Calc-Test_P_00038_LEFT_CC_1/1.3.6.1.4.1.9590.1...,Calc-Test_P_00038_LEFT_CC_1/1.3.6.1.4.1.9590.1...
1,P_00038,2,LEFT,MLO,1,calcification,PUNCTATE-PLEOMORPHIC,CLUSTERED,4,BENIGN,2,Calc-Test_P_00038_LEFT_MLO/1.3.6.1.4.1.9590.10...,Calc-Test_P_00038_LEFT_MLO_1/1.3.6.1.4.1.9590....,Calc-Test_P_00038_LEFT_MLO_1/1.3.6.1.4.1.9590....
2,P_00038,2,RIGHT,CC,1,calcification,VASCULAR,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00038_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_00038_RIGHT_CC_1/1.3.6.1.4.1.9590....,Calc-Test_P_00038_RIGHT_CC_1/1.3.6.1.4.1.9590....
3,P_00038,2,RIGHT,CC,2,calcification,VASCULAR,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00038_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_00038_RIGHT_CC_2/1.3.6.1.4.1.9590....,Calc-Test_P_00038_RIGHT_CC_2/1.3.6.1.4.1.9590....
4,P_00038,2,RIGHT,MLO,1,calcification,VASCULAR,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00038_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_00038_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_00038_RIGHT_MLO_1/1.3.6.1.4.1.9590...

## Prepare labels
Combine metadata tables and keep source information.

In [11]:
print("COMBINING ALL CSV FILES")

# Add source_file column to each dataframe
mass_train['source_file'] = 'mass_train'
mass_test['source_file'] = 'mass_test'
calc_train['source_file'] = 'calc_train'
calc_test['source_file'] = 'calc_test'

print("Added 'source_file' column to each dataframe")

# Concatenate all dataframes
combined_df = pd.concat([
    mass_train,
    mass_test,
    calc_train,
    calc_test
], ignore_index=True)

print("Concatenated all dataframes")
print("Combined dataframe created")

COMBINING ALL CSV FILES
Added 'source_file' column to each dataframe
Concatenated all dataframes
Combined dataframe created

## Inspect metadata
Check combined dataframe structure and columns.

In [12]:
print("COMBINED DATAFRAME SUMMARY")

print(f"\nTotal rows: {combined_df.shape[0]:,}")
print(f"Total columns: {combined_df.shape[1]}")

print(f"\nColumn names ({len(combined_df.columns)}):")
for i, col in enumerate(combined_df.columns, 1):
    print(f"  {i:2d}. {col}")

COMBINED DATAFRAME SUMMARY

Total rows: 3,568
Total columns: 18

Column names (18):
   1. patient_id
   2. breast_density
   3. left or right breast
   4. image view
   5. abnormality id
   6. abnormality type
   7. mass shape
   8. mass margins
   9. assessment
  10. pathology
  11. subtlety
  12. image file path
  13. cropped image file path
  14. ROI mask file path
  15. source_file
  16. breast density
  17. calc type
  18. calc distribution

In [13]:
print("First 10 rows of combined dataframe:")
combined_df.head(10)

First 10 rows of combined dataframe:

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,source_file,breast density,calc type,calc distribution
0,P_00001,3.0,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,mass_train,NaN,NaN,NaN
1,P_00001,3.0,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,mass_train,NaN,NaN,NaN
2,P_00004,3.0,LEFT,CC,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,mass_train,NaN,NaN,NaN
3,P_00004,3.0,LEFT,MLO,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,mass_train,NaN,NaN,NaN
4,P_00004,3.0,RIGHT,MLO,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,mass_train,NaN,NaN,NaN
5,P_00009,3.0,RIGHT,CC,1,mass,OVAL,ILL_DEFINED,4,MALIGNANT,4,Mass-Training_P_00009_RIGHT_CC/1.3.6.1.4.1.959...,Mass-Training_P_00009_RIGHT_CC_1/1.3.6.1.4.1.9...,Mass-Training_P_00009_RIGHT_CC_1/1.3.6.1.4.1.9...,mass_train,NaN,NaN,NaN
6,P_00009,3.0,RIGHT,MLO,1,mass,OVAL,ILL_DEFINED,4,MALIGNANT,4,Mass-Training_P_00009_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00009_RIGHT_MLO_1/1.3.6.1.4.1....,Mass-Training_P_00009_RIGHT_MLO_1/1.3.6.1.4.1....,mass_train,NaN,NaN,NaN
7,P_00015,3.0,LEFT,MLO,1,mass,IRREGULAR,ILL_DEFINED-SPICULATED,4,MALIGNANT,4,Mass-Training_P_00015_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00015_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00015_LEFT_MLO_1/1.3.6.1.4.1.9...,mass_train,NaN,NaN,NaN
8,P_00018,2.0,RIGHT,CC,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00018_RIGHT_CC/1.3.6.1.4.1.959...,Mass-Training_P_00018_RIGHT_CC_1/1.3.6.1.4.1.9...,Mass-Training_P_00018_RIGHT_CC_1/1.3.6.1.4.1.9...,mass_train,NaN,NaN,NaN
9,P_00018,2.0,RIGHT,MLO,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00018_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00018_RIGHT_MLO_1/1.3.6.1.4.1....,Mass-Training_P_00018_RIGHT_MLO_1/1.3.6.1.4.1....,mass_train,NaN,NaN,NaN

In [14]:
print("DISTRIBUTION BY SOURCE FILE")

print("\nNumber of cases from each CSV:")
print(combined_df['source_file'].value_counts())

DISTRIBUTION BY SOURCE FILE

Number of cases from each CSV:
source_file
calc_train    1546
mass_train    1318
mass_test      378
calc_test      326
Name: count, dtype: int64

## Check label distribution
Inspect pathology label counts used for classification.

In [15]:
print("PATHOLOGY DISTRIBUTION")

if 'pathology' in combined_df.columns:
    print("\nDiagnosis label counts:")
    pathology_counts = combined_df['pathology'].value_counts()
    print(pathology_counts)
    
    print("\nPercentage distribution:")
    pathology_pct = combined_df['pathology'].value_counts(normalize=True) * 100
    for label, pct in pathology_pct.items():
        print(f"  {label}: {pct:.2f}%")
else:
    print("\n'pathology' column not found in dataframe")

PATHOLOGY DISTRIBUTION

Diagnosis label counts:
pathology
MALIGNANT                  1457
BENIGN                     1429
BENIGN_WITHOUT_CALLBACK     682
Name: count, dtype: int64

Percentage distribution:
  MALIGNANT: 40.84%
  BENIGN: 40.05%
  BENIGN_WITHOUT_CALLBACK: 19.11%

## Inspect metadata
Check BI-RADS assessment value distribution.

In [16]:
print("ASSESSMENT DISTRIBUTION (BI-RADS)")

if 'assessment' in combined_df.columns:
    print("\nAssessment category counts:")
    assessment_counts = combined_df['assessment'].value_counts().sort_index()
    print(assessment_counts)
    
    print("\nBI-RADS categories:")
    print("  0 = Incomplete")
    print("  1 = Negative")
    print("  2 = Benign")
    print("  3 = Probably Benign")
    print("  4 = Suspicious")
    print("  5 = Highly Suggestive of Malignancy")
else:
    print("\n'assessment' column not found in dataframe")

ASSESSMENT DISTRIBUTION (BI-RADS)

Assessment category counts:
assessment
0     238
1       3
2     644
3     477
4    1633
5     573
Name: count, dtype: int64

BI-RADS categories:
  0 = Incomplete
  1 = Negative
  2 = Benign
  3 = Probably Benign
  4 = Suspicious
  5 = Highly Suggestive of Malignancy

## Prepare labels
Convert the pathology values into binary labels so the dataset can be used for a binary classification model (benign vs malignant).

In [17]:
print("Label column identification")

if 'pathology' in combined_df.columns:
    print("Label column found: pathology")

    # Clean pathology text
    pathology_clean = combined_df['pathology'].astype(str).str.strip().str.upper()

    # Keep valid classes
    valid_mask = pathology_clean.str.contains('BENIGN|MALIGNANT', na=False)
    filtered_df = combined_df.loc[valid_mask].copy()
    pathology_clean = pathology_clean.loc[valid_mask]

    # Convert pathology to binary label (0=benign, 1=malignant)
    filtered_df['label'] = pathology_clean.apply(lambda x: 1 if 'MALIGNANT' in x else 0)

    # Save cleaned dataframe
    combined_df = filtered_df

    print(f"Rows after label filtering: {len(combined_df)}")
    print("Binary label mapping: BENIGN -> 0, MALIGNANT -> 1")

    missing_labels = combined_df['label'].isna().sum()
    print(f"Missing values in label: {missing_labels}")
else:
    print("Error: 'pathology' column not found")
    print("Available columns:")
    for col in combined_df.columns:
        print(f"- {col}")

Label column identification
Label column found: pathology
Rows after label filtering: 3568
Binary label mapping: BENIGN -> 0, MALIGNANT -> 1
Missing values in label: 0

## Check label distribution
Summarize metadata size and label counts.

In [18]:
print("Metadata summary")

print(f"Total rows: {combined_df.shape[0]:,}")
print(f"Total columns: {combined_df.shape[1]}")

print("Dataset composition:")
for source in combined_df['source_file'].unique():
    count = (combined_df['source_file'] == source).sum()
    print(f"- {source}: {count:,}")

if 'pathology' in combined_df.columns:
    print("Pathology distribution:")
    for label in combined_df['pathology'].unique():
        count = (combined_df['pathology'] == label).sum()
        pct = (count / len(combined_df)) * 100
        print(f"- {label}: {count:,} ({pct:.1f}%)")

if 'label' in combined_df.columns:
    print("Binary label distribution:")
    print(combined_df['label'].value_counts().sort_index())

Metadata summary
Total rows: 3,568
Total columns: 19
Dataset composition:
- mass_train: 1,318
- mass_test: 378
- calc_train: 1,546
- calc_test: 326
Pathology distribution:
- MALIGNANT: 1,457 (40.8%)
- BENIGN: 1,429 (40.1%)
- BENIGN_WITHOUT_CALLBACK: 682 (19.1%)
Binary label distribution:
label
0    2111
1    1457
Name: count, dtype: int64